[tool.bandit]
skips = ["B101"]

[tool.mypy]
ignore_missing_imports = true
namespace_packages = false

[tool.ruff.lint]
ignore = ["E501"]
select = ["F", "E", "W", "I001", "B"]

[tool.ruff.lint.isort]
known-third-party = ["streamlit","google-generativeai","google-auth","google-api-python-client","PyPDF2","supabase","boto3","fpdf","PyPDF2","markdown2"]
