[theme]
# Color principal para botones y elementos interactivos
primaryColor="#395caa"

# Color de fondo del área principal (blanco)
backgroundColor="#FFFFFF"

# Color de fondo de la barra lateral y otros elementos (gris claro)
secondaryBackgroundColor="#F0F2F6"

# Color del texto (negro)
textColor="#262730"
