[theme]
primaryColor="#395caa"
backgroundColor="#395caa"
secondaryBackgroundColor="#395caa"
textColor="#fafafa"

#[theme]
#primaryColor="#395caa"
#backgroundColor="#fafafa"
#secondaryBackgroundColor="#e0e8f8"
#textColor="#000000"
